name: Publish to GitHub Packages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Change this to the Node.js version you're using

      - name: yarn Install dependencies
        run: yarn

      - name: Build dist
        run: npm run build

      - name: Build Docs
        run: npm run docs:build

      - name: Publish to npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN_PROFILE }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist # Change this to the directory you want to deploy
